# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gs < Formula
  desc "A small, opinionated stacked-diff tool for git."
  homepage "https://gitstack.sh"
  version "0.7.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.5/gitstack_0.7.5_darwin_amd64.tar.gz"
      sha256 "6a09af898e205e1195f98a9fb2a45b777e1c6e476b74d4d21e42a8f52369d1dc"

      define_method(:install) do
        bin.install "gs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.5/gitstack_0.7.5_darwin_arm64.tar.gz"
      sha256 "7019ff59a8cc5e708c76d4228d6eab4c768a871f684a640f9881f7b7709e5623"

      define_method(:install) do
        bin.install "gs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.5/gitstack_0.7.5_linux_amd64.tar.gz"
      sha256 "ceb56519d6a40feea2ee7735090cbc9a350afd50f0ec74765474dbba809cfd5a"
      define_method(:install) do
        bin.install "gs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.5/gitstack_0.7.5_linux_arm64.tar.gz"
      sha256 "ca3d14c5aadc59dacb8ce2c0facb76eac2ecf979d4f02d8cce0b9416826db721"
      define_method(:install) do
        bin.install "gs"
      end
    end
  end

  conflicts_with "ghostscript"

  def caveats
    <<~EOS
      GitStack installs `gs`, which shares a name with Ghostscript's `gs`.
      If you also need Ghostscript, install GitStack via the script instead:
        curl -fsSL https://gitstack.sh/install.sh | sh
    EOS
  end

  test do
    system "#{bin}/gs", "version"
  end
end
