# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gs < Formula
  desc "A small, opinionated stacked-diff tool for git."
  homepage "https://gitstack.sh"
  version "0.7.4"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.4/gitstack_0.7.4_darwin_amd64.tar.gz"
      sha256 "997dc32b62592308c591a69eb65aa20bb0c51a44c73d918e088f4eae28929d2b"

      define_method(:install) do
        bin.install "gs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.4/gitstack_0.7.4_darwin_arm64.tar.gz"
      sha256 "e2dfec4ad834e580e6377eef2404a5ddb698dcb792f1e654881ffcbe4c9bf2e1"

      define_method(:install) do
        bin.install "gs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.4/gitstack_0.7.4_linux_amd64.tar.gz"
      sha256 "d2bf5b3b3f948958409046e12c4d52aa82c13d7415841fc149f96e79598b715f"
      define_method(:install) do
        bin.install "gs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.4/gitstack_0.7.4_linux_arm64.tar.gz"
      sha256 "7829a46f2ef003c18cc8658e341ad303d33b198c58f3178c1c19a302ef5ae3a9"
      define_method(:install) do
        bin.install "gs"
      end
    end
  end

  conflicts_with "ghostscript"

  def caveats
    <<~EOS
      GitStack installs `gs`, which shares a name with Ghostscript's `gs`.
      If you also need Ghostscript, install GitStack via the script instead:
        curl -fsSL https://gitstack.sh/install.sh | sh
    EOS
  end

  test do
    system "#{bin}/gs", "version"
  end
end
