# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gs < Formula
  desc "A small, opinionated stacked-diff tool for git."
  homepage "https://gitstack.sh"
  version "0.7.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.1/gitstack_0.7.1_darwin_amd64.tar.gz"
      sha256 "f518dd0b36ba32fefc59d82592512f1e06eb26435352843ccf6686aa078b6407"

      define_method(:install) do
        bin.install "gs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.1/gitstack_0.7.1_darwin_arm64.tar.gz"
      sha256 "ae384d6b25eb26bb55db4e28779af6bc405853926936808ec19ea4683cae47a3"

      define_method(:install) do
        bin.install "gs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.1/gitstack_0.7.1_linux_amd64.tar.gz"
      sha256 "dadf8fe31ffcc689c8840d1979e04b5d88e201761fe2304af384d4d27253468d"
      define_method(:install) do
        bin.install "gs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alethi-dev/gitstack-releases/releases/download/v0.7.1/gitstack_0.7.1_linux_arm64.tar.gz"
      sha256 "26dbec13ed4f255e7fae8c8402dae555144ae722507a1b1b0298b0a199896e4e"
      define_method(:install) do
        bin.install "gs"
      end
    end
  end

  conflicts_with "ghostscript"

  def caveats
    <<~EOS
      GitStack installs `gs`, which shares a name with Ghostscript's `gs`.
      If you also need Ghostscript, install GitStack via the script instead:
        curl -fsSL https://gitstack.sh/install.sh | sh
    EOS
  end

  test do
    system "#{bin}/gs", "version"
  end
end
